package eu.anticom.eva.event;

public enum EventType {
    //default event type. no special semantics
    DEFAULT,
    //a null event (don't know yet, whether it is usefull)
    NULL,
    //input recieved (usually generated by input channels)
    INPUT,
    //request output (usually generated by processors and handled by output channels)
    OUTPUT,
    //request to re-handle the event later
    TIMED,
    //some context has changed (usually generated either by an input channel and handled by a processor)
    CONTEXT_CHANGED;
}
